### ISSUE TITLE
Listview Item Click

### ISSUE THREAD

**Issue by deviprasadchinni** [codinguniverse-de/grouped_listview#1]
Hi,
How to handle click event for list item.

**Comment by codinguniverse-de** [comment]
Hi,
you can easily use the onTap property of the ListTile.
Example:
`return GroupedListView<Group, String>(
                   collection: [Group("Test1", 1), Group("Test2", 2), Group("Test1", 3),],
                   groupBy: (Group g) => g.groupName,
                   listBuilder: (BuildContext context, Group g) => ListTile(
                       title: Text(g.value.toString(),
                       onTap: () {
                           // Your function here
                       })),
                   groupBuilder: (BuildContext context, String name) => Text(name),
           );`
